### ISSUE TITLE
Use `require('jspm').Builder`

### ISSUE THREAD

**Issue by guybedford** [akikoo/universal-react-systemjs-jspm#1]
Nice work. Is it making sense mostly? I'd suggest using `var Builder = require('jspm').Builder` in the bundler as this is the fully-jspm-configured builder instance, which covers all cases. This is especially important in jspm 0.17 (which I'd highly advise using too).

**Comment by akikoo** [comment]
Thanks @guybedford for the feedback, it's highly valuable! Good news about jspm 0.17. 

I'm however still a bit unsure how bundling works. I've changed bundler after your comments but I can't get the CSS included. What am I missing?

**Comment by akikoo** [comment]
@guybedford If I understood correctly I need to use ES6 `import` [https://github.com/akikoo/universal-react-systemjs-jspm/commit/dc5e9a2d2ae685af547312269390f6eb180734b9] rather than `System.import` in my entry points to make CSS bundling work?

**Comment by guybedford** [comment]
Yes System.import statements are not traced for builds pending issue https://github.com/systemjs/builder/issues/452. You'd need to add them manually otherwise - `bundle('src/client/index.js + src/shared/components/Card/Card.js')`.

**Comment by akikoo** [comment]
Thanks @guybedford for confirming that. After upgrading to jspm 0.17 beta I'm getting this error: `Unable to fetch "npm:babel-core@6.5.2". Only file URLs of the form file:/// allowed running in Node.` Not sure how to fix that, any thoughts?

**Comment by guybedford** [comment]
@akikoo make sure you are including the jspm.browser.js file before the jspm.config.js file.
